app/urls.py
from django.contrib import admin
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('main/', views.funding_main,name='funding_main'),
    path('contact/', views.assemble,name='assemble'),
    path('funding/', views.funding_join,name='funding_join'),

    path('shop/', views.shop,name='shop'),
    path('shop-single/', views.shop_single,name='shop_single'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# from django.conf.urls import (
#     handler404, handler400, handler500
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('app/user/', include('user.urls')),
    path('app/fund/', include('fundingapp.urls')),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

# handler404 = "app.views.page_not_found_page"

fundingapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *

app_name = 'fundingapp'

urlpatterns = [

    path('detail/<int:board_id>', views.detail, name='detail'),
    path('select/<int:select_drop>', views.select,name='select'),
    path('contact/<int:board_id>', views.contact, name='contact'),


    path('create1/', Create1.as_view(),name='create1'),
    path('create2/', Create2.as_view(),name='create2'),
    path('create3/', Create3.as_view(),name='create3'),
    path('download/<str:file_path>', views.download, name='download'),
    path('allViewPage/<int:page_num>/<int:board_id>/',AllViewPage.as_view(), name="allViewPage"),


    path('ADDTeam/', ADDTeams.as_view(),name='ADDTeam'),
    # path('AllViewPage/<int:board_id>/<int:page_num>/',AllViewPage.as_view(),name="modify")
    # path('AllViewPage/',AllViewPage.as_view(),name="AllViewPage")
]

user/urls.py
from django.contrib import admin
from django.urls import path
from user import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('signin/', views.signin,name='signin'),
    path('signout/', views.signout,name='signout'),
    path('signup/', views.signup,name='signup'),
    path('usercheck/', views.usercheck,name='usercheck'),
    path('pwchange/', views.pwchange,name='pwchange'),
    path('myfunding/', views.myfunding, name='myfunding'),
    path('myboarding/', views.myboarding, name='myboarding'),

]

templates/banner.html
{% load static %} 


<!-- Start Banner Hero -->
<div id="template-mo-zay-hero-carousel" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
        <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="0" class="active"></li>
        <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="1"></li>
        <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="2"></li>
        {% comment %} <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="3"></li> {% endcomment %}
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="container">
                <div class="row p-5">
                    <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                        <!--이미지 부분 -->
                        <img class="img-fluid" src="/static/assets/img/동행.png" alt="">
                        <div class="h4" style="margin:1rem 0rem;"><br></div>
                    </div>
                    <div class="col-lg-6 mb-0 d-flex align-items-center">
                        <div class="text-align-left align-self-center">
                            <h1 class="h1 text-success" style="font-family: 'NanumSquareEB';" ><b>22년부터<br> WAT과 함께가자!</b></h1>
                            <p style="margin:1rem 0rem; font-family: 'NanumSquareR';">
                                앞으로 개발자들에게는 이전과 다른 프로젝트의 끝맺음을 맞이할 수 있는 기회의 플랫폼을 서포터들에게는 색다른 아이디어로 태어난 기획을 펀딩함으로써 사용할수 있는 플랫폼을 제공하여 개발자들이 기획을 펼칠 수 있는 플랫폼입니다.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% comment %} <div class="carousel-item">
            <div class="container">
                <div class="row p-5">
                    <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                        <img class="img-fluid" src="/static/assets/img/2022year.jpg" alt="">
                        <h3 class="h4" style="text-align:center;margin:1rem 0rem; font-family: 'NanumSquareEB';"> You are not Alone, We are Together </h3>
                    </div>
                    <div class="col-lg-6 mb-0 d-flex align-items-center">
                        <div class="text-align-left align-self-center">
                            <h1 class="h1 text-success" style="font-family: 'NanumSquareEB';" ><b>22년부터<br> WAT과 함께가자!</b></h1>
                            <p style="margin:1rem 0rem; font-family: 'NanumSquareR';">
                                앞으로 개발자들에게는 이전과 다른 프로젝트의 끝맺음을 맞이할 수 있는 기회의 플랫폼을 서포터들에게는 색다른 아이디어로 태어난 기획을 펀딩함으로써 사용할수 있는 플랫폼을 제공하여 개발자들이 기획을 펼칠 수 있는 플랫폼입니다.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div> {% endcomment %}
        <div class="carousel-item ">
            <div class="container">
                <div class="row p-5">
                    <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                        {% comment %} <img class="img-fluid" src="/static/assets/img/2022year.jpg" alt=""> {% endcomment %}
                        {% comment %} <img class="img-fluid" src="https://ww.namu.la/s/0826fcb62ab5ffd031695083aa629d99351834b91417a1c9fee4a2a1a4b64bd8287e88163820b02176526fe7006fb51438fbb6f42cb2438497e298e722eac77cde9da7d51d8fa4d36800670013fb43b70d35328129d1f9aec0f9a5ee05ae7fe4" alt=""> {% endcomment %}
                        <img class="img-fluid" src="/static/assets/img/도전해라.png" alt="" style="height:443.35px;">
                        <div class="h4" style="margin:1rem 0rem;"><br></div>
                    </div>
                    <div class="col-lg-6 mb-0 d-flex align-items-center">
                        <div class="text-align-left">
                            <h1 class="h1 text-success" style="font-family: 'NanumSquareEB';"><b>프로젝트 펀딩도전 <br>Let's get it !</b></h1>
                            <p style="margin:1rem 0rem; font-family: 'NanumSquareR';">
                                펀딩 도전을 함으로써 당신의 프로젝트가 사람들에게 가치있는 프로젝트가 되어 끝을 아름답게 맺게될 것 입니다.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="container">
                <div class="row p-5">
                    <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                        <img class="img-fluid" src="/static/assets/img/펀딩해라.png" alt=""  style="height:443.35px;">
                        <div class="h4" style="margin:1rem 0rem;"><br></div>
                    </div>
                    <div class="col-lg-6 mb-0 d-flex align-items-center">
                        <div class="text-align-left">
                            <h1 class="h2 text-success" style="font-family: 'NanumSquareEB';"><b>신기하고 유용하고 재미있는</b></h1>
                            <h3 class="h3" style="font-family: 'NanumSquareEB';">프로젝트에 서포터가 되어 개발자들을 응원해주세요</h3>
                            <p style="margin:1rem 0rem; font-family: 'NanumSquareR';">
                                응원이 새로운 세상, 새로운 변화를 맞이할 수 있는 원동력이 될 것 입니다.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev text-decoration-none w-auto ps-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="prev">
        <i class="fas fa-chevron-left"></i>
    </a>
    <a class="carousel-control-next text-decoration-none w-auto pe-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="next">
        <i class="fas fa-chevron-right"></i>
    </a>
</div>

templates/base.html
<!DOCTYPE html>
 <html lang="ko">
    {% include 'head.html' %}
    <body>
        {% include 'header.html' %} 

        {% block content %} 
        {% endblock %} 
        
        {% include 'footer.html' %}
        
    </body>
</html>

templates/footer.html
{%load static%}
<!-- Start Footer -->
<footer class="bg-dark" id="tempaltemo_footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4 pt-5">
        <h2 class="h2 text-success border-bottom pb-3 border-light logo">
          WAT Developer
        </h2>
      </div>
    </div>

    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
      rel="stylesheet"
    />
    <div class="container">
      <div class="row">
        <div class="col-md-2 mx-3">
          <div class="card user-card">
            <div class="card-block">
              <div class="user-image">
                <img
                  src='{% static "assets/img/jongwon.png" %}'
                  class="img-radius"
                  alt="User-Profile-Image"
                />
              </div>
              <h6
                style="font-family: NanumSquareR"
                class="f-w-600 m-t-25 m-b-10"
              >
                김종원
              </h6>

              <p style="font-family: NanumSquareR" class="m-t-15 text-muted">
                KT AIVLE 1기
              </p>
              <hr />
              <div class="row justify-content-center user-social-link">
                <div class="col-auto">
                  <a href="#!"><i class="fa fa-facebook text-facebook"></i></a>
                </div>
                <div class="col-auto">
                  <a href="https://github.com/JONWON2"
                    ><i class="fa fa-github text-github"></i
                  ></a>
                </div>
                <div class="col-auto">
                  <a href="#!"><i class="fa fa-dribbble text-dribbble"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-2 mx-3">
          <div class="card user-card">
            <div class="card-block">
              <div class="user-image">
                <img
                  src='{% static "assets/img/minjin.png" %}'
                  class="img-radius"
                  alt="User-Profile-Image"
                />
              </div>
              <h6
                style="font-family: NanumSquareR"
                class="f-w-600 m-t-25 m-b-10"
              >
                신민진
              </h6>

              <p style="font-family: NanumSquareR" class="m-t-15 text-muted">
                KT AIVLE 1기
              </p>
              <hr />
              <div class="row justify-content-center user-social-link">
                <div class="col-auto">
                  <a href="#!"><i class="fa fa-facebook text-facebook"></i></a>
                </div>
                <div class="col-auto">
                  <a href="https://github.com/Shinminjin"
                    ><i class="fa fa-github text-github"></i
                  ></a>
                </div>
                <div class="col-auto">
                  <a href="#!"><i class="fa fa-dribbble text-dribbble"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-2 mx-3">
          <div class="card user-card">
            <div class="card-block">
              <div class="user-image">
                <img
                  src='{% static "assets/img/sungwoo.png" %}'
                  class="img-radius"
                  alt="User-Profile-Image"
                />
              </div>
              <h6
                style="font-family: NanumSquareR"
                class="f-w-600 m-t-25 m-b-10"
              >
                장성우
              </h6>

              <p style="font-family: NanumSquareR" class="m-t-15 text-muted">
                KT AIVLE 1기
              </p>
              <hr />
              <div class="row justify-content-center user-social-link">
                <div class="col-auto">
                  <a href="#!"><i class="fa fa-facebook text-facebook"></i></a>
                </div>
                <div class="col-auto">
                  <a href="https://github.com/CastleRain"
                    ><i class="fa fa-github text-github"></i
                  ></a>
                </div>
                <div class="col-auto">
                  <a href="#!"><i class="fa fa-dribbble text-dribbble"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-2 mx-3">
          <div class="card user-card">
            <div class="card-block">
              <div class="user-image">
                <img
                  src='{% static "assets/img/yeongin.png" %}'
                  class="img-radius"
                  alt="User-Profile-Image"
                />
              </div>
              <h6
                style="font-family: NanumSquareR"
                class="f-w-600 m-t-25 m-b-10"
              >
                장영인
              </h6>

              <p style="font-family: NanumSquareR" class="m-t-15 text-muted">
                KT AIVLE 1기
              </p>
              <hr />
              <div class="row justify-content-center user-social-link">
                <div class="col-auto">
                  <a href="#!"><i class="fa fa-facebook text-facebook"></i></a>
                </div>
                <div class="col-auto">
                  <a href="https://github.com/youngine"
                    ><i class="fa fa-github text-github"></i
                  ></a>
                </div>
                <div class="col-auto">
                  <a href="#!"><i class="fa fa-dribbble text-dribbble"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-2 mx-3">
          <div class="card user-card">
            <div class="card-block">
              <div class="user-image">
                <img
                  src='{% static "assets/img/sangeun.png" %}'
                  class="img-radius"
                  alt="User-Profile-Image"
                />
              </div>
              <h6
                style="font-family: NanumSquareR"
                class="f-w-600 m-t-25 m-b-10"
              >
                조상은
              </h6>

              <p style="font-family: NanumSquareR" class="m-t-15 text-muted">
                KT AIVLE 1기
              </p>
              <hr />
              <div class="row justify-content-center user-social-link">
                <div class="col-auto">
                  <a href="#!"><i class="fa fa-facebook text-facebook"></i></a>
                </div>
                <div class="col-auto">
                  <a href="https://github.com/sejoe-dct"
                    ><i class="fa fa-github text-github"></i
                  ></a>
                </div>
                <div class="col-auto">
                  <a href="#!"><i class="fa fa-dribbble text-dribbble"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  <div class="w-100 bg-black py-3">
    <div class="container">
      <div class="row pt-2">
        <div class="col-12">
          <p class="text-left text-light" style="font-family: NanumSquareR">
            Copyright &copy;
            <a rel="sponsored" href="https://github.com/youngine/waat" target="_blank"
              >WAT-Repository</a
            >
             |  Designed by 2022 KT AIVLE 부산 경남 1반 4조 
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- End Footer -->

<!-- Start Script -->
<script src='{% static "assets/js/jquery-1.11.0.min.js" %}'></script>
<script src='{% static "assets/js/jquery-migrate-1.2.1.min.js" %}'></script>
<script src='{% static "assets/js/bootstrap.bundle.min.js" %}'></script>
<script src='{% static "assets/js/templatemo.js" %}'></script>
<script src='{% static "assets/js/custom.js" %}'></script>
<!-- End Script -->

templates/form_errors.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<!-- 필드 오류를 출력한다. -->
<div class="alert alert-danger">
<strong>{{ field.label }}</strong>
{{ error }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<!-- 넌필드 오류를 출력한다. -->
<div class="alert alert-danger">
<strong>{{ error }}</strong>
</div>
{% endfor %}
{% endif %}

templates/head.html
{%load static%}
<head>
  <title>개발자를 위한 창고(WAT)</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link
    rel="apple-touch-icon"
    href='{% static "assets/img/apple-icon.png" %}'
  />
  <link
    rel="shortcut icon"
    type="image/x-icon"
    href='{% static "assets/img/favicon.ico" %}'
  />

  <link rel="stylesheet" href='{% static "assets/css/bootstrap.min.css" %}' />
  <link rel="stylesheet" href='{% static "assets/css/templatemo.css" %}' />
  <link rel="stylesheet" href='{% static "assets/css/custom.css" %}' />
  <link href='{% static "assets/css/signin.css"%}' rel="stylesheet" />
  <link href='{% static "assets/css/profile.css"%}' rel="stylesheet" />
  <link href='{% static "assets/css/myfunding.css"%}' rel="stylesheet" />
 
  <!-- Load fonts style after rendering the layout styles -->
  <link
    rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap"
  />
  <link rel="stylesheet" href='{% static "assets/css/fontawesome.min.css" %}' />

  <!-- 펀딩 참여에 쓰인 head 정보-->
  <link
    rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
    crossorigin="anonymous"
  />
  <link rel="stylesheet" href="/static/assets/css/fund_view.css" />

  <!--
    
TemplateMo 559 Zay Shop

https://templatemo.com/tm-559-zay-shop

-->
  {% comment %} 나눔글씨체 한글 {% endcomment %}
  <style>
    @font-face {
      font-family: "NanumSquareR";
      src: local("NanumSquareR"),
        url("{% static 'assets/fonts/NanumSquareR.ttf' %}") format("opentype");
    }
    @font-face {
      font-family: "NanumSquareEB";
      src: local("NanumSquareEB"),
        url("{% static 'assets/fonts/NanumSquareEB.otf' %}") format("opentype");
    }
    @font-face {
      font-family: "NanumSquareB";
      src: local("NanumSquareB"),
        url("{% static 'assets/fonts/NanumSquareB.otf' %}") format("opentype");
    }
    @font-face {
      font-family: "NanumSquareR";
      src: local("NanumSquareR"),
        url("{% static 'assets/fonts/NanumSquareR.otf' %}") format("opentype");
    }
  </style>
  <!-- DEFAULT CSS LINK-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'assets/css/base.css' %}"
  />
</head>

templates/header.html
{%load static%}

<body>
    
    <!-- Start Script -->
    <script src='{% static "assets/js/jquery-1.11.0.min.js" %}'></script>
    <script src='{% static "assets/js/jquery-migrate-1.2.1.min.js" %}'></script>
    <script src='{% static "assets/js/bootstrap.bundle.min.js" %}'></script>
    <script src='{% static "assets/js/templatemo.js" %}'></script>
    <script src='{% static "assets/js/custom.js" %}'></script>
    <!-- End Script -->

    {% comment %} 본문 헤더 내용 {% endcomment %}
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">
            
            {% comment %} 로고 부분 {% endcomment %}
            <a class="navbar-brand text-success logo h1 align-self-center" a href="{% url 'app:funding_main' %}">
                WAT
            </a>
            
            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                {% comment %} 카테고리 부분 {% endcomment %}
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex">
                        <li class="nav-item">
                            <a class="nav-link" style="font-family: 'NanumSquareEB';margin: 0rem 2.4rem;" a href="{% url 'fundingapp:create1' %}">펀딩신청</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-family: 'NanumSquareEB';margin: 0rem 2.4rem;" a href="/app/fund/select/1">펀딩참여</a>
                        </li>
                        <!-- <li class="nav-item">
                            <a class="nav-link" style="font-family: 'NanumSquareEB';margin: 0rem 2.4rem;" a href="{% url 'app:assemble' %}">게시판</a>
                        </li> -->
                    </ul>
                
                </div>
                <div class="navbar align-self-center d-flex">
                    {% if request.session.user %}
                        <div class="mx-2" style="font-family:NanumSquareR;">{{ request.session.user }}님 반갑습니다.</div> 
                        <a style="font-family:NanumSquareR; text-decoration-line : none;margin:0rem 1rem;" a href="{% url 'user:myfunding' %}"> 마이페이지 </a>
                        <a style="font-family:NanumSquareR; text-decoration-line : none;margin:0rem 1rem;" id = "signout" a href="{% url 'user:signout' %}"> 로그아웃 </a>
                    {%else%}
                        <a style="font-family:NanumSquareR; text-decoration-line : none;margin:0rem 1rem;" a href="{% url 'user:signin' %}"> 로그인 </a>
                        <a style="font-family:NanumSquareR; text-decoration-line : none;margin:0rem 1rem;"a href="{% url 'user:signup' %}"> 회원가입 </a>
                    {% endif %}
                    </div>
                </div>
                <script>
                    document.querySelector("#signout").addEventListener("click", (e) => {
                        if (confirm("로그아웃 하시겠습니까?")) {
                            alert("로그아웃 되셨습니다.");
                        } else {
                            e.preventDefault();
                            alert("취소하셨습니다.");
                        }
                      });
                </script>
            </div>
        </div>
    </nav>
</body>
    <!-- Close Header -->

templates/header_origin.html
{%load static%}

<body>
    {% comment %} 메일정보랑 전화번호는 필요없다고 판단하여 주석처리하였다.  -종원
    <!-- Start Top Nav -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
        <div class="container text-light">
            <div class="w-100 d-flex justify-content-between">
                <div>
                    <i class="fa fa-envelope mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                    <i class="fa fa-phone mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                </div>
                <div>
                    <a class="text-light" href="https://fb.com/templatemo" target="_blank" rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://twitter.com/" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin fa-sm fa-fw"></i></a>
                </div>
            </div>
        </div>
    </nav> 
    <!-- Close Top Nav -->
    {% endcomment %}

    {% comment %} 본문 헤더 내용 {% endcomment %}
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">
            
            {% comment %} 로고 부분 {% endcomment %}
            <a class="navbar-brand text-success logo h1 align-self-center" a href="{% url 'funding_challenge' %}">
                WAT
            </a>
            {% comment %} 쓰이는 부분이 없는데 왜 있을까요? 빼도 괜찮을것 같은데 ㅎㅎ -종원 {% endcomment %}
            {% comment %} <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button> {% endcomment %}

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                {% comment %} 카테고리 부분 {% endcomment %}
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex">
                        <li class="nav-item">
                            <a class="nav-link" style="font-family: 'NanumSquareEB';margin: 0rem 2.4rem;" a href="{% url 'funding_challenge' %}">펀딩도전</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-family: 'NanumSquareEB';margin: 0rem 2.4rem;" a href="{% url 'funding_join' %}">펀딩참여</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-family: 'NanumSquareEB';margin: 0rem 2.4rem;" a href="{% url 'assemble' %}">팀원모집</a>
                        </li>
                        {% comment %}
                        펀딩도전, 펀딩참여, 팀모집으로 3개 뿐이니 한개는 제거해도 된다고 판단 -종원 
                            <li class="nav-item">
                                <a class="nav-link" a href="{% url 'shop' %}">Shop</a>
                            </li> 
                        {% endcomment %}
                    </ul>
                
                </div>
                {% comment %} 검색 마이페이지 장바구니 부분 {% endcomment %}
                <div class="navbar align-self-center d-flex">
                    {% comment %} <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
                        <div class="input-group">
                            <input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">
                            <div class="input-group-text">
                                <i class="fa fa-fw fa-search"></i>
                            </div>
                        </div>
                    </div> {% endcomment %}
                    
                    {% comment %} <a class="nav-icon position-relative text-decoration-none" href="#">
                        <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
                        <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">7</span>
                    </a>
                    <a class="nav-icon position-relative text-decoration-none" href="#">
                        <i class="fa fa-fw fa-user text-dark mr-3"></i>
                        <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">+99</span>
                    </a> {% endcomment %}
                    
                    <a style="font-family:NanumSquareR; text-decoration-line : none;margin:0rem 1rem;" href="#"> 로그인 </a>
                    <a style="font-family:NanumSquareR; text-decoration-line : none;margin:0rem 1rem;" href="#"> 회원가입 </a>

                    </div>
                </div>
            </div>

        </div>
    </nav>
    <!-- Close Header -->

templates/tab.html
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active mx-3">
          <a style="font-family:NanumSquareR;" class="nav-link" href="{% url 'user:myfunding' %}">내 펀딩목록 <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item mx-3">
          <a style="font-family:NanumSquareR;"class="nav-link" href="{% url 'user:myboarding' %}">내 게시물</a>
        </li>
        <li class="nav-item mx-3">
          <a style="font-family:NanumSquareR;" class="nav-link" href="{% url 'user:usercheck' %}">비밀번호 변경</a>
        </li>
      </ul>
    </div>
  </nav>